#!/usr/bin/env bash

# if [ -n "$AWS_BUCKET" ]; then
#   cat << EOF > .s3cfg
# [default]
# access_key = ${AWS_ACCESS_KEY}
# secret_key = ${AWS_SECRET_KEY}
# EOF
#   if [ -d world ]; then
#     s3cmd sync world/ s3://${AWS_BUCKET}/world/
#   else
#     mkdir -p world
#     cd world
#     s3cmd get --recursive s3://${AWS_BUCKET}/world/
#     cd ..
#   fi
#   rm .s3cfg
# fi
if [ -d world ]; then
  echo -n "Save world... "
  gdrive -a ~/service-account.json upload world/ ${DRIVE_WORLD_ID}
else
  echo -n "Load world... "
  mkdir -p world
  cd world
  gdrive -a ~/service-account.json download ${DRIVE_WORLD_ID} .
  cd ..
fi